const $ = s => document.querySelector(s);
const state = { data: null };
const n = (v, d = 2) => Number.isFinite(Number(v)) ? Number(v).toLocaleString('zh-CN', { minimumFractionDigits: d, maximumFractionDigits: d }) : '--';
const pct = v => Number.isFinite(Number(v)) ? `${Number(v) >= 0 ? '+' : ''}${Number(v).toFixed(2)}%` : '--';
const tone = v => Number(v) > 0 ? 'positive' : Number(v) < 0 ? 'negative' : 'neutral';
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
const text = (id, value) => { const el = $(id); if (el) el.textContent = value; };
function clock() { text('#clock', new Date().toLocaleTimeString('zh-CN', { hour12:false })); if (state.data?.market.liveUpdatedAt) text('#freshness', `联网报价 · ${Math.max(0, Math.round((Date.now() - new Date(state.data.market.liveUpdatedAt)) / 1000))} 秒前`); }
function liveAsset(f, old, provider) { const value=Number(f[0]), previous=Number(f[7]), date=f[12], time=f[6]; if (!Number.isFinite(value)) throw Error('invalid quote'); const candle={date,open:Number(f[2]),high:Number(f[4]),low:Number(f[5]),close:value}; return {...old,value,previous,change:previous ? (value/previous-1)*100 : old.change,open:candle.open,high:candle.high,low:candle.low,quoteTime:`${date} ${time}`,provider,candles:[...(old.candles||[]).filter(x=>x.date!==date),candle].slice(-30)}; }
function addPoint(asset) { const now=new Date().toISOString(); asset.intraday=[...(asset.intraday||[]).filter(x=>Date.now()-new Date(x.time).getTime()<86400000),{time:now,value:asset.value}].slice(-288); }
function getTencent() { return new Promise((resolve,reject)=>{ const old=$('#tencentQuote'); if(old) old.remove(); const s=document.createElement('script'); s.id='tencentQuote'; s.src=`https://qt.gtimg.cn/q=hf_GC,hf_XAU&_=${Date.now()}`; const timer=setTimeout(()=>{s.remove();reject(Error('timeout'));},8000); s.onload=()=>{clearTimeout(timer);resolve([window.v_hf_GC,window.v_hf_XAU]);}; s.onerror=()=>{clearTimeout(timer);reject(Error('load failed'));}; document.head.appendChild(s); }); }
async function refreshLive(data) { try { const [gc,xau] = await getTencent(); const m=data.market; m.gold=liveAsset(String(gc).split(','),m.gold,'腾讯全球期货行情 · COMEX GC（实时）'); m.spotGold=liveAsset(String(xau).split(','),m.spotGold||{},'腾讯全球期货行情 · 伦敦现货 XAU（实时）'); addPoint(m.gold); const fx=Number(m.fx?.value); if(Number.isFinite(fx)) { const value=m.spotGold.value*fx/31.1034768,old=m.domesticReference||{}; m.domesticReference={value,change:old.value?(value/old.value-1)*100:0,quoteTime:m.spotGold.quoteTime,provider:'伦敦现货 × USD/CNY 折算的国内人民币克价参考'}; } m.liveUpdatedAt=new Date().toISOString(); if(data.goldForecast) data.goldForecast.marketDate=String(gc).split(',')[12]; return true; } catch(e) { console.warn('quote unavailable',e); return false; } }
function renderKpis(m) { const rows=[['COMEX 黄金主连 · 实时',m.gold,'USD/OZ'],['伦敦现货黄金 · 实时',m.spotGold,'USD/OZ'],['国内金价参考 · 人民币克价',m.domesticReference,'CNY/G']]; $('#kpiRibbon').innerHTML=rows.map(([name,a,u])=>`<article class="kpi"><small><span>${name}</span><span>${u}</span></small><strong>${n(a?.value)}</strong><em class="${tone(a?.change)}">${pct(a?.change)}</em><p>${esc(a?.quoteTime||'公开行情计算中')}</p></article>`).join(''); }
function setupCanvas(el) { const r=el.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2); el.width=Math.max(1,r.width*d);el.height=Math.max(1,r.height*d);const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);return [c,r.width,r.height]; }
function drawIntraday(asset) { const el=$('#intradayChart'), p=(asset.intraday||[]).filter(x=>Number.isFinite(Number(x.value))).slice(-288); if(!el||p.length<2)return; const [c,w,h]=setupCanvas(el),v=p.map(x=>+x.value),lo=Math.min(...v),hi=Math.max(...v),span=Math.max(.1,hi-lo),x=i=>8+i*(w-16)/(p.length-1),y=q=>10+(hi-q)/span*(h-28); c.clearRect(0,0,w,h);c.beginPath();p.forEach((q,i)=>i?c.lineTo(x(i),y(q.value)):c.moveTo(x(i),y(q.value)));c.strokeStyle='#f6deb0';c.lineWidth=1.6;c.stroke();text('#intradayRange',`${n(lo)} — ${n(hi)} USD/OZ`);text('#intradayStart',p[0].time.slice(11,16));text('#intradayEnd',p.at(-1).time.slice(11,16)); }
function drawDaily(asset) { const el=$('#stockChart'),rows=(asset.candles||[]).slice(-30);if(!el||rows.length<2)return;const[c,w,h]=setupCanvas(el),v=rows.map(x=>+x.close),lo=Math.min(...v),hi=Math.max(...v),span=Math.max(.1,hi-lo),x=i=>45+i*(w-105)/(rows.length-1),y=q=>18+(hi-q)/span*(h-65);c.clearRect(0,0,w,h);c.beginPath();rows.forEach((r,i)=>i?c.lineTo(x(i),y(r.close)):c.moveTo(x(i),y(r.close)));c.strokeStyle='#d3a64e';c.lineWidth=1.6;c.stroke();$('#chartTimeline').innerHTML='<b>走势时间</b>'+[0,7,14,21,rows.length-1].filter((v,i,a)=>a.indexOf(v)===i&&rows[v]).map(i=>`<span>${rows[i].date.slice(5).replace('-','月')}日</span>`).join(''); }
function renderNews(news) { const items=(news.items||[]).filter(x=>x.category==='黄金'); $('#newsTimeline').innerHTML=items.length?items.map(x=>`<a class="news-item" href="${esc(x.url)}" target="_blank" rel="noopener"><time>${esc(x.time)}</time><div><h3>${esc(x.title)}</h3><p>${esc(x.summary||'公开黄金资讯')}</p><span>${esc(x.source||'公开来源')}</span></div></a>`).join(''):'<div class="news-item"><div>等待下一次公开资讯更新</div></div>'; }
function renderExperts(data) { const items=data.weeklyExpertUpdates?.length?data.weeklyExpertUpdates:(data.experts||[]); $('#expertGrid').innerHTML=items.slice(0,3).map(x=>`<article class="expert-card"><small>${esc(x.institution)}</small><h3>${esc(x.expert)}</h3><p>${esc(x.view)}</p><footer><span>${esc(x.date)} · ${esc(x.source)}</span><a href="${esc(x.url)}" target="_blank" rel="noopener">查看原文 ↗</a></footer></article>`).join(''); text('#expertStamp',data.deployment?.expertWeeklyUpdatedAt ? `最近更新 ${new Date(data.deployment.expertWeeklyUpdatedAt).toLocaleString('zh-CN')}` : '每 6 小时公开源更新'); }
function render(data) { state.data=data;const m=data.market,a=m.gold,f=data.goldForecast||{};renderKpis(m);text('#systemState',m.liveUpdatedAt?'公网行情已连接':'公开快照加载中');text('#heroSymbol',`${a.symbol||'GC'} · ${a.name||'COMEX 黄金主连'}`);text('#heroValue',n(a.value));text('#heroChange',pct(a.change));$('#heroChange').className=tone(a.change);text('#heroOpen',n(a.open));text('#heroHigh',n(a.high));text('#heroLow',n(a.low));text('#heroAmplitude',n(m.spotGold?.value));text('#heroAmount',a.quoteTime||'--');text('#forecastDate',`${f.marketDate||'--'} · ${f.horizon||'未来 1—5 日'}`);text('#regime',f.bias||'等待模型更新');text('#confidence',f.confidence||'--');text('#forecastNarrative',f.action||'基于公开行情的规则化情景');text('#baseCaseTarget',`${n(f.expectedRange?.[0],1)} — ${n(f.expectedRange?.[1],1)}`);text('#goldSupport',`${n(f.support,1)} USD/OZ`);text('#goldResistance',`${n(f.resistance,1)} USD/OZ`);renderNews(data.news||{});renderExperts(data);drawDaily(a);drawIntraday(a);clock(); }
async function load(){try{const r=await fetch(`./data/dashboard.json?t=${Date.now()}`,{cache:'no-store'});const data=await r.json();await refreshLive(data);render(data);}catch(e){console.error(e);text('#systemState','数据连接暂不可用');}}
$('#refreshBtn').onclick=load;$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();setInterval(clock,1000);setInterval(()=>state.data&&refreshLive(state.data).then(()=>render(state.data)),15000);setInterval(load,300000);load();
