const $ = s => document.querySelector(s);
const COLORS={gold:'#e6b85c',gold2:'#ffd978',cyan:'#8dd8d6',up:'#f27663',down:'#6dcf9d',grid:'rgba(255,255,255,.08)',muted:'#8b9293'};
const state={data:null,resizeTimer:null};
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d,maximumFractionDigits:d}):'--';
const pct=v=>Number.isFinite(Number(v))?`${Number(v)>0?'+':''}${Number(v).toFixed(2)}%`:'--';
const tone=v=>Number(v)>0?'positive':Number(v)<0?'negative':'neutral';
const esc=v=>{const n=document.createElement('i');n.textContent=v??'';return n.innerHTML};
const avg=a=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);
const ma=(v,p,i=v.length-1)=>avg(v.slice(Math.max(0,i-p+1),i+1));
function canvas(el){const r=el.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);el.width=Math.max(1,Math.round(r.width*d));el.height=Math.max(1,Math.round(r.height*d));const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);return{c,w:r.width,h:r.height}}
function clock(){const now=new Date();$('#clock').textContent=now.toLocaleTimeString('zh-CN',{hour12:false});if(state.data){const age=Math.max(0,Math.round((Date.now()-new Date(state.data.market.updatedAt))/1000));$('#freshness').textContent=state.data.deployment?`部署快照 · ${new Date(state.data.deployment.generatedAt).toLocaleString('zh-CN')}`:`${age}秒前`}}
function renderKpis(m){const cmb=m.cmbGold||{}, domestic=m.domesticGold||{};const items=[
  {n:'COMEX 黄金主连',s:m.gold,v:m.gold.value,p:m.gold.change,u:'USD/OZ'},
  {n:'伦敦现货黄金',s:m.spotGold,v:m.spotGold.value,p:m.spotGold.change,u:'USD/OZ'},
  {n:'招商银行 Au99.99',s:cmb,v:cmb.value,p:cmb.change,u:'CNY/G'},
  {n:'上金所 Au99.99',s:m.chinaGold,v:m.chinaGold.value,p:m.chinaGold.change,u:'CNY/G'},
  {n:'国际现货折算',s:domestic,v:domestic.theoreticalCnyGram,p:null,u:'CNY/G'},
  {n:'跨市场溢价 / 折价',s:domestic,v:domestic.premiumPct,p:domestic.premiumPct,u:'%'}];
  $('#kpiRibbon').innerHTML=items.map(x=>`<article class="kpi"><small><span>${esc(x.n)}</span><span>${esc(x.u)}</span></small><strong>${num(x.v,x.u==='%'?3:2)}</strong>${x.p!==null?`<em class="${tone(x.p)}">${pct(x.p)}</em>`:''}<p>${esc(x.s?.quoteTime||x.s?.provider||'快照参考')}</p></article>`).join('')}
function drawPrice(asset){const rows=(asset.candles||[]).slice(-30);if(!rows.length)return null;const{c,w,h}=canvas($('#stockChart')),L=48,R=64,T=26,B=h-24,plot=w-L-R;const closes=rows.map(x=>x.close),m5=rows.map((_,i)=>ma(closes,5,i)),m10=rows.map((_,i)=>ma(closes,10,i)),m20=rows.map((_,i)=>ma(closes,20,i));let lo=Math.min(...rows.map(x=>x.low),...m20),hi=Math.max(...rows.map(x=>x.high),...m20),pad=(hi-lo)*.08;lo-=pad;hi+=pad;const y=v=>T+(hi-v)/(hi-lo)*(B-T),x=i=>L+(i+.5)*plot/rows.length,step=plot/rows.length; c.font='8px DM Mono';for(let i=0;i<5;i++){let py=T+(B-T)*i/4,v=hi-(hi-lo)*i/4;c.beginPath();c.moveTo(L,py);c.lineTo(w-R,py);c.strokeStyle=COLORS.grid;c.stroke();c.fillStyle=COLORS.muted;c.fillText(v.toFixed(0),w-R+7,py+3)}
  rows.forEach((r,i)=>{const col=r.close>=r.open?COLORS.up:COLORS.down,px=x(i);c.strokeStyle=col;c.beginPath();c.moveTo(px,y(r.high));c.lineTo(px,y(r.low));c.stroke();c.fillStyle=col;c.fillRect(px-step*.28,y(Math.max(r.open,r.close)),step*.56,Math.max(1,y(Math.min(r.open,r.close))-y(Math.max(r.open,r.close))))});
  [[m5,COLORS.cyan],[m10,COLORS.gold],[m20,'#c5a8ff']].forEach(([a,col])=>{c.beginPath();a.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.strokeStyle=col;c.lineWidth=1.2;c.stroke()});
  const current=asset.value;c.setLineDash([4,4]);c.beginPath();c.moveTo(L,y(current));c.lineTo(w-R,y(current));c.strokeStyle=COLORS.gold2;c.stroke();c.setLineDash([]);return{rows,m5:m5.at(-1),m20:m20.at(-1),low:Math.min(...rows.slice(-20).map(x=>x.low)),high:Math.max(...rows.slice(-20).map(x=>x.high))}}
function renderHero(m){const a=m.gold,r=drawPrice(a),spot=m.spotGold||{};$('#heroSymbol').textContent=`${a.symbol} · ${a.name}`;$('#heroValue').textContent=num(a.value);$('#heroChange').textContent=pct(a.change);$('#heroChange').className=tone(a.change);$('#heroOpen').textContent=num(a.open);$('#heroHigh').textContent=num(a.high);$('#heroLow').textContent=num(a.low);$('#heroAmplitude').textContent=num(spot.value);$('#heroAmount').textContent=a.quoteTime||'--';const verify=m.goldVerification||{},ok=verify.state==='verified';$('#goldVerification').textContent=ok?`多源已核验 · 最大偏差 ${Number(verify.maxDeviationPct).toFixed(3)}%`:'多源报价复核中';if(!r){$('#stockEmpty').classList.add('show');return}$('#stockEmpty').classList.remove('show');const up=a.value>r.m5&&r.m5>r.m20,down=a.value<r.m5&&r.m5<r.m20;$('#trendConclusion').textContent=up?'价格与短中期均线同向上行':down?'价格与短中期均线同向下行':'均线交错，等待方向确认';$('#trendConclusion').className=up?'positive':down?'negative':'neutral';$('#maRelation').textContent=`${num(r.m5)} / ${num(r.m20)}`;$('#range20').textContent=`${num(r.low)} — ${num(r.high)}`}
function drawProjection(m,f){const el=$('#projectionChart'),{c,w,h}=canvas(el),current=m.gold.value,atr=Math.max(1,Number(f.atr)||current*.012),bias=(f.scenarios.bull-f.scenarios.bear)/100;const base=[current,current+bias*atr*.25,current+bias*atr*.55,current+bias*atr*.72],upper=base.map((v,i)=>v+atr*(.3+i*.18)),lower=base.map((v,i)=>v-atr*(.3+i*.18)),L=18,R=18,T=14,B=h-14,all=[...upper,...lower],lo=Math.min(...all),hi=Math.max(...all),x=i=>L+i*(w-L-R)/3,y=v=>T+(hi-v)/(hi-lo)*(B-T);for(let i=0;i<4;i++){c.beginPath();c.moveTo(x(i),T);c.lineTo(x(i),B);c.strokeStyle='rgba(255,255,255,.05)';c.stroke()}c.beginPath();upper.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));lower.slice().reverse().forEach((v,i)=>c.lineTo(x(3-i),y(v)));c.closePath();c.fillStyle='rgba(230,184,92,.12)';c.fill();[[upper,'#f27663'],[base,'#ffd978'],[lower,'#6dcf9d']].forEach(([arr,col])=>{c.beginPath();arr.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.strokeStyle=col;c.lineWidth=1.5;c.stroke()});c.fillStyle=COLORS.gold2;c.beginPath();c.arc(x(0),y(base[0]),3,0,Math.PI*2);c.fill();$('#projectionNote').textContent=`中性轨迹以当前价为起点：未来 1—5 日的预期区间为 ${num(f.expectedRange?.[0],1)} — ${num(f.expectedRange?.[1],1)} USD/OZ；阴影表示规则化波动带，而非确定价格。`}
function renderForecast(m,f){$('#regime').textContent=f.bias;$('#confidence').textContent=f.confidence;$('#forecastDate').textContent=`${f.marketDate||'--'} · ${f.horizon||'未来1—5日'}`;drawProjection(m,f);const s=f.scenarios||{};[['bull',s.bull],['base',s.base],['bear',s.bear]].forEach(([k,v])=>{$(`#${k}Bar`).style.width=`${v||0}%`;$(`#${k}Value`).textContent=`${v||0}%`});$('#goldSupport').textContent=`${num(f.support,1)} USD/OZ`;$('#goldResistance').textContent=`${num(f.resistance,1)} USD/OZ`;$('#goldMa20').textContent=`${num(f.expectedRange?.[0],1)} — ${num(f.expectedRange?.[1],1)}`;const insights=[['执行框架',f.action,f.triggerUp],['关键条件',`支撑 ${num(f.support,1)} / 压力 ${num(f.resistance,1)}`,f.triggerDown],['驱动反馈',(f.drivers||[]).join(' · '),`方法：${f.methodology}`]];$('#insightStack').innerHTML=insights.map((x,i)=>`<article class="signal" style="--tone:${[COLORS.gold,COLORS.cyan,COLORS.down][i]}"><small>0${i+1} · ${esc(x[0])}</small><strong>${esc(x[1])}</strong><p>${esc(x[2])}</p></article>`).join('');$('#invalidation').textContent=`${f.disclaimer||''} ${f.invalidation||''}`}
function renderNews(news){const gold=(news.items||[]).filter(x=>x.category==='黄金');$('#newsTimeline').innerHTML=gold.length?gold.map(x=>`<a class="news-item" href="${esc(x.url||'#')}" target="_blank" rel="noopener"><time>${esc(x.time)}</time><div><h3>${esc(x.title)}</h3><p>${esc(x.summary||'黄金市场相关资讯')}</p><span>${esc(x.source||'来源待标注')} · ${x.sentiment==='positive'?'偏多影响':x.sentiment==='negative'?'偏空影响':'持续观察'}</span></div></a>`).join(''):'<div class="news-item"><div>暂无黄金资讯</div></div>'}
function renderReference(m){const c=m.cmbGold||{},s=m.chinaGold||{},d=m.domesticGold||{},primary=Number.isFinite(c.value)?c:s;$('#cmbGold').textContent=Number.isFinite(c.value)?`${num(c.value)} 元/克`:'--';$('#cmbTime').textContent=c.status==='live'?`${c.quoteTime} · 招行官网黄金市场行情`:'官方接口当前不可用';$('#goldChange').textContent=pct(primary.change);$('#goldChange').className=tone(primary.change);$('#sgeGold').textContent=`${num(s.value)} 元/克`;$('#sgeTime').textContent=`${s.quoteTime||'--'} · 上金所官方延时`;$('#convertedGold').textContent=`${num(d.theoreticalCnyGram)} 元/克`;const p=Number.isFinite(primary.value)&&d.theoreticalCnyGram?(primary.value/d.theoreticalCnyGram-1)*100:d.premiumPct;$('#domesticPremium').textContent=pct(p);$('#correlation').textContent=num(m.fx?.value,4);$('#sourceVerification').innerHTML=`口径说明：${esc(c.scope||'招商银行官网黄金市场行情')}。该项不是招行账户金客户买入/卖出成交价。 <a href="${esc(c.sourceUrl||'https://m.cmbchina.com/goldrate.html')}" target="_blank" rel="noopener">查看招商银行行情</a> · <a href="https://www.sge.com.cn/sjzx/yshqbg" target="_blank" rel="noopener">查看上金所延时行情</a>`}
function render(data){state.data=data;const m=data.market;renderKpis(m);renderHero(m);renderForecast(m,data.goldForecast||{});renderNews(data.news||{items:[]});renderReference(m);$('#systemState').textContent=data.deployment?'公开静态研究展示':'数据链路在线';$('#dataStamp').textContent=`快照生成：${data.deployment?.generatedAt?new Date(data.deployment.generatedAt).toLocaleString('zh-CN'):m.updatedAt}`;clock()}
async function load(){try{const r=await fetch(`./data/dashboard.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);render(await r.json())}catch(e){console.error(e);$('#systemState').textContent='数据快照不可用'}}
$('#refreshBtn').onclick=load;$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();window.addEventListener('resize',()=>{clearTimeout(state.resizeTimer);state.resizeTimer=setTimeout(()=>state.data&&render(state.data),120)});setInterval(clock,1000);load();
